application: cd-efolix
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /efolix/assets
  static_dir: efolix/assets
  expiration: "1d 0m"


- url: /(.+\.(gif|png|jpg|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true


- url: .*
  script: index.php
